
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: oktts1
      POSTGRES_USER: oktts
      POSTGRES_PASSWORD: oktts
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U oktts -d oktts"]
      interval: 5s
      timeout: 3s
      retries: 20
    ports:
      - "5432:5432"
    networks:
      - okdtts_net  
  web:
    build: .
    # command: gunicorn django_ledger_project.wsgi:application --bind 0.0.0.0:8000
    environment:
      DJANGO_SETTINGS_MODULE: django_ledger_project.settings  # make this explicit
    volumes:
      - static_volume:/app/static
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - okdtts_net

  

  nginx:
    image: nginx:latest
    depends_on:
      - web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static_volume:/static
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/www/certbot:/var/www/certbot
    networks:
      - okdtts_net

volumes:
  db_data:
  static_volume:
networks:
  okdtts_net:
    external: true
